name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Skip draft PRs to reduce unnecessary runs
    branches-ignore:
      - 'draft/**'
      - 'wip/**'

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # Changed from read to write
      issues: write         # Changed from read to write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Add explicit GitHub token
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Performance optimizations
          timeout_minutes: 5
          max_turns: 3
          allowed_tools: "View,Grep,Edit"

          # Streamlined prompt for faster processing
          direct_prompt: |
            Review this PR focusing on code quality and Python best practices. Be concise.

            Key areas: implementation patterns, error handling, testing approach.
