name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # Changed from read to write
      issues: write         # Changed from read to write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Add explicit GitHub token
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Direct prompt for automated review
          direct_prompt: |
            Please review this pull request for the claude-slash Python refactor project and provide feedback on:
            - Code quality and Python best practices
            - Project structure and packaging
            - Command implementation patterns
            - Error handling and user experience
            - Testing approach
            - Documentation quality

            Be constructive and focus on the Python migration from bash scripts.
