name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Fail fast if tests take too long
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use latest for speed
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    
    - name: Run all tests
      run: make test
    
    - name: Upload coverage to Codecov
      if: github.event_name == 'push'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    
    - name: Run linting
      run: make lint
    
    - name: Check code formatting
      run: |
        black --check --diff .
        isort --check-only --diff .

  fast-test:
    runs-on: ubuntu-latest
    timeout-minutes: 1  # Ultra-fast subset for immediate feedback
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock
    
    - name: Run syntax validation
      run: |
        python -m py_compile github_init_command.py
        python -m py_compile register_command.py
        python -c "import test_fast, test_integration_fast, test_github_init_command"
    
    - name: Run fastest unit tests only
      run: make test-fast